### ISSUE TITLE
redirect after sign in

### ISSUE THREAD

**Issue by afhammad** [lynndylanhurley/redux-auth#12]
is there a way to redirect to a certain path after using email sign in?

**Comment by Secretmapper** [comment]
Check this out: https://github.com/joshgeller/react-redux-jwt-auth-example

**Comment by afhammad** [comment]
That example doesn't seem to be using redux-auth at all.

**Comment by Secretmapper** [comment]
The same idea can be applied for redux-auth. This is what I'm using in my app.

For example, if you see `checkAuth` in `AuthenticatedComponent` it's using a `props.isAuthenticated` property. Since `redux-auth` uses `Immutable`, the api needs to change slightly.

```
  checkAuth () {
    if (!this.props.auth.getIn(['user', 'isSignedIn'])) {
      let redirectAfterLogin = this.props.location.pathname
      this.props.pushPath(`/login?next=${redirectAfterLogin}`)
    }
  }
```

Then on the `LoginView` I just render `<Theme.EmailSignInForm />` that dispatches `pushPath` once logged in.

**Comment by afhammad** [comment]
All that makes sense, i guess what's confusing me is the ?next query string. who is that being handled by?

**Comment by lynndylanhurley** [comment]
@afhammad - see [here](https://github.com/lynndylanhurley/redux-auth/blob/master/docs/api-expectations/email-sign-up.md#confirm_success_url). 

This isn't documented or tested yet, but you can set this manually by passing a method called `confirmationSuccessUrl` to the configuration settings. For example, assuming your target redirect is "http://custom-redirect.com", try the following configuration:

~~~js
// client-side usage
store.dispatch(configure(
  {apiUrl: "https://api.com"},
  {confirmationSuccessUrl: () => "http://custom-redirect.com"}
).then(() => {
  // render app
});
~~~

I have a ton of customizable settings like this planned, and some of them may currently work, but I'm waiting until I have better test coverage to document them.

I haven't really tested this - if it doesn't work let me know and I'll push a fix ASAP.

**Comment by lynndylanhurley** [comment]
@afhammad - i think I may have misunderstood this issue. I'm working on adding a `next` parameter to the `EmailSignInForm` and `OAuthSignInButton` components. This param will accept a path that will be redirected to upon successful login.
