### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by pupadupa** [lynndylanhurley/redux-auth#129]
Account page could be visible in inspector (even without auth):
https://yadi.sk/i/32IfYz6_3Nnhuj (screenshot)

All sensetive data shouldn't be placed inside component without auth check on server side (or during api call).

I guess it should be mentioned explicitly.

**Comment by wesley-harding** [comment]
I don't see the issue here. What you're showing is simply the JS source behind the account page. There is no sensitive data on that page. Any data that would be displayed on that page should be loaded via an AJAX call to the server.

**Comment by lynndylanhurley** [comment]
Thanks @wesley-harding. That's just the code for the template. Any actual sensitive data should be served by the API and protected with access control server-side.
