### ISSUE TITLE
Question: http/https SecurityError in popup.  Am I approaching wrong?

### ISSUE THREAD

**Issue by SpencerCDixon** [lynndylanhurley/redux-auth#21]
This might be a question for StackOverflow and if you'd like me to post there I'd be happy to.  I used redux-auth as a guide to setting up OAuth though so I thought someone here might be able to answer my question with better context...

So I'm trying to do google oauth to get a refresh token for my users (not actually using google oauth to save the user).  I had everything working when I used the client side OAuth for google api but they don't provide a refresh token when you do that handshake, only an access_token.  So I set up omniauth on my rails server to make the flow go like this:

user clicks authenticate with google --> popup in screen goes to backend server --> backend server redirects to google oauth --> they authenticate and get redirected to backend server's callback --> backend server saves token for appropriate user and then redirects back to client side app on localhost:3000 (nothing needs to be done on client, just need the token saved on my server)

I do however need to know that the authentication was successful so I can dispatch appropriate actions.  In redux-auth you check for the `access_token` inside the popup.location URI.  Problem is when I use this server side popup flow I get this nasty http/https error:

![screen shot 2016-01-31 at 7 44 03 pm](https://cloud.githubusercontent.com/assets/7471018/12725299/10071926-c8e0-11e5-9b4d-6b3d7dec358b.png)

If instead of redirecting back to the client I just redirect to a view in my backend server I could then have a script on that page that just does `window.close()` but that seems hacky to me.  Another potential solution I was thinking was to try and use the `window.postMessage` api but I don't know if that has great browser support/also seems hacky.

I feel like I'm just approaching this whole flow completely wrong or I'm missing something obvious.  If anyone has any thoughts or could give me some direction that would be much appreciated!!

**Comment by lynndylanhurley** [comment]
`postMessage` is broken on nearly every version of IE. I'm not sure if even edge supports it when CORS is involved.

In this library, 

1. the parent window opens a popup to the API. It starts checking the URL of the popup every 100 ms or so.
2. The API redirects to the OAuth provider (google, facebook, etc.).
3. The provider redirects back to the API..
4. The API redirects back to the client, appending the auth credentials to the URL.

At this point the parent window is allowed to access popup's the URL because it's on the same domain. The parent window then takes the auth credentials from the URL and verifies them with the API.

This approach should work all the way back to IE8 and maybe even earlier.

**Comment by SpencerCDixon** [comment]
> At this point the parent window is allowed to access popup's the URL because it's on the same domain. 

Isn't the api server on a different domain?  For example, my rails server is at localhost:3001 but my react/redux app is at localhost:3000.  Do you get that same protocol error it just goes away once the api server redirects to the client with the proper params?

**Comment by SpencerCDixon** [comment]
Yeah nevermind, I must have been really tired when I was trying to get this working sunday night because it seems to work fine now haha.  I think logging the popup when it was coming from the other URI (like https;//accounts.google) was throwing me off by giving that SecurityError,  thank you for taking the time to explain the process to me @lynndylanhurley and the great work with this library.  Without this library I wouldn't have been able to get this working!  Closing issue

**Comment by lynndylanhurley** [comment]
> Isn't the api server on a different domain?

@SpencerCDixon - the API will need to redirect back to the client domain.

**Comment by SpencerCDixon** [comment]
Yeah that totally fixed it, thanks again!
