### ISSUE TITLE
How can I override and customize components. 

### ISSUE THREAD

**Issue by Prashant31** [lynndylanhurley/redux-auth#25]
In fact how do I redirect after signin. Can't find it in the documentation

**Comment by jflayhart** [comment]
As far as customizing, I would love to have the ability to toggle between using a pop up modal, which is default alerts right now, or actual bootstrap alert banners that are closable. I really like this plugin, but can't really use it until there are more customization options.

**Comment by lynndylanhurley** [comment]
@jflayhart - I will accept a PR for that feature if you have time.

**Comment by jflayhart** [comment]
It might be a while, but I might have some time in the next month or so to work on it :) Happy to contribute. I am, however, new to redux but learning quickly.

**Comment by lynndylanhurley** [comment]
>In fact how do I redirect after signin. Can't find it in the documentation

Just added a `next` property to the forms. You can pass in a function to be called on success. For example:

```jsx
<EmailSignInForm next={() => browserHistory.push('/account')} />
```

This will redirect users to the `/account` page once sign-in is successful.
