### ISSUE TITLE
Custom submit labels

### ISSUE THREAD

**Issue by stroborobo** [lynndylanhurley/redux-auth#28]
We've always used the terms "Log in" and "Register" for our apps, so it's more distinguishable. I wanted to set that custom label for the submit button in EmailSignInForm, but apparently [that's not possible][1]. Those lines could just be replaced by `{this.props.inputProps.submit.text || 'Sign In'}`, right?

PS: You don't have some TypeScript definition files lying around for this project, do you? :)

Have a good one!

[1]: https://github.com/lynndylanhurley/redux-auth/blob/5cf8601/src/views/default/EmailSignInForm.js#L80

**Comment by lynndylanhurley** [comment]
@stroborobo - this is a good idea. Do you have time to submit a PR?

**Comment by stroborobo** [comment]
No, sorry, we've moved to redux-auth-wrapper for JWT now. I missed that this is made for a ruby gem and we're no Ruby guys here.

**Comment by lynndylanhurley** [comment]
Will be fixed by #3.
