### ISSUE TITLE
Material theme doesn't work with 0.15 version of material-ui

### ISSUE THREAD

**Issue by hyzhak** [lynndylanhurley/redux-auth#30]
Because Material-UI changed Colors file:

so before you should did:

```javascript
import Colors from 'material-ui/lib/styles/colors'; 
//use somewhere
Colors.darkBlack
```

but now:

```javascript
import { darkBlack } as Colors from 'material-ui/lib/styles/colors';.
```

you can check it here https://github.com/callemall/material-ui/pull/2825

**Comment by ochervak** [comment]
any updates on this ?

**Comment by ochervak** [comment]
how can i fix it ?

**Comment by yannickschuchmann** [comment]
Maybe it isn't already done due material-ui v0.15 is only in alpha state and updating material-ui could have other side effects? not sure..

**Comment by yannickschuchmann** [comment]
I just tried to update material-ui but since v0.14.3 I get:
```
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function but got: undefined
```
This may happen because of a broken import statement. Unfortunately I haven't found it yet.
v0.14.2 works like a charm for me.. I checked the changelog of 0.14.3.. no idea

**Comment by tayden-hakai** [comment]
+1. Also having issues with broken paths

**Comment by aleks-sidorenko** [comment]
+1

**Comment by lynndylanhurley** [comment]
Please try version `0.0.3-beta3`. The tests are failing, but I've been testing everything manually and it all seems to work.

**Comment by lynndylanhurley** [comment]
Working as of `0.0.3-beta6`.
