### ISSUE TITLE
Wrong Request Method

### ISSUE THREAD

**Issue by leon-wbr** [lynndylanhurley/redux-auth#40]
The forms try to send the request with "OPTIONS" method, but my Rails API can't find a route to match that. I'm not sure if I'm doing something wrong, but it's not working, I'm getting this error:

    Started OPTIONS "/auth/sign_in" for ::1 at 2016-04-03 22:57:00 +0200
    ActionController::RoutingError (No route matches [OPTIONS] "/auth/sign_in")
    ...

Using standard devise_token_auth gem.

Edit: Seems this issue could be on my end, due to local CORS. Does anyone know a solution anyway?

**Comment by yury-dymov** [comment]
My config.ru file, which is working for me:

```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
run Rails.application

# allow cross origin requests
require 'rack/cors'
use Rack::Cors do
  allow do
    origins '*'
    resource '*',
      :headers => :any,
      :expose => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
      :methods => [:get, :post, :options, :delete, :put]
  end
end

```

**Comment by lynndylanhurley** [comment]
@yury-dymov is right - this is a CORS issue. Thanks @yury-dymov!
