### ISSUE TITLE
server side code ?

### ISSUE THREAD

**Issue by feesjah** [lynndylanhurley/redux-auth#5]
Hi, first of all, awesome project! 
Is there an example of the api code somewhere? I can't seem to find it.

**Comment by vincentbriglia** [comment]
fairly certain that it's this one https://github.com/lynndylanhurley/devise_token_auth_demo

**Comment by feesjah** [comment]
hmm, any chance of giving more info for node.js users ? like how to generate the tokens with regards to device etc.

**Comment by lynndylanhurley** [comment]
Hi @feesjah - have you read the [API expectations documentation](https://github.com/lynndylanhurley/redux-auth#extended-documentation)?

**Comment by feesjah** [comment]
Sorry, I must be missing something.

```
Success Response Headers

...
client

string

The client token is used to identify device (browser client, phone, tablet, etc) of the current session. This allows us to maintain multiple concurrent sessions across devices / browsers.
```
where is the code, or the instructions to create the client token or generate access token ? All I see is what should be returned, but not how to create the return values. Again sorry, I am pretty new to the node.js/ react.js scene, I know how to encode and sign a token, but have not learned those things to identify device etc.

**Comment by lynndylanhurley** [comment]
There is not currently a node.js implementation that I'm aware of.

If you're implementing your own API, I would recommend following the existing [ruby gem](https://github.com/lynndylanhurley/devise_token_auth). Maybe at some point I will create a node.js implementation, but I don't have any immediate plans to do so.

[Bcrypt](https://github.com/dcodeIO/bcrypt.js) should be used to generate the access tokens for security reasons. You can generate the client ids using something simpler like [UUIDs](https://github.com/broofa/node-uuid).

**Comment by jure** [comment]
To sum it up, if you replicate the `devise_token_auth` external API, by following the outlined API expectations, `redux-auth` will work and work equally well, talking to a Node.js implementation. At least that's what I'm doing.

@lynndylanhurley what, in your opinion, is going to be the trickiest aspect of this API to replicate?
