### ISSUE TITLE
Question: How this lib would work with dynamic subdomains

### ISSUE THREAD

**Issue by betoharres** [lynndylanhurley/redux-auth#52]
Hi all,
I'm currently developing a ``rails`` project that users ``devise_token_auth`` gem and ``apartment`` gem as well, for multi-tenancy.

The thing is, ``apartment gem`` offers this feature os setting your desired tenant with ``subdomains``, and looking at the docs I see that you set the your API as a constant in the configuration of the app. 

I'm curious to know if there's a easy workaround for this. Any suggestions? Thanks in advance!

**Comment by lynndylanhurley** [comment]
I don't fully understand your use-case, but it sounds like could try multi-user configuration, using a different user-type for each subdomain:
https://github.com/lynndylanhurley/redux-auth#multiple-user-type-configuration
