### ISSUE TITLE
Credentials not saved on login

### ISSUE THREAD

**Issue by stephenmmcleod** [lynndylanhurley/redux-auth#54]
Hi there!  Thanks for the hard work on this project, just browsing the source has already helped me a bunch.  Unfortunately, however, I can't seem to get this to function correctly when validating on my fake API.

The problem I am experiencing is that when I attempt a sign_in action, the react app is authenticated, however if I refresh the page the state does not persist.  I have read through issue #50  and this may be part of the problem however I have noticed that the auth-token doesn't actually get read (and therefore is never saved).

Specifically, in utils/fetch.js when updateAuthCredentials is called, the resp.headers object doesn't contain any values (so persisData doesn't get called further down)

The following is my current (fake/testing) node api server, which seems to responds with the correct headers when I hit it with postman.  What am I missing?

	var jsonServer = require('json-server')
	var R = require('ramda')
	var faker = require('faker')
	var nLoop = R.range(0)
	var util = require('util')
	const jwt = require('jsonwebtoken')
	const moment = require('moment')

	function aPerson() {
		return {
			first: faker.name.firstName(),
			last: faker.name.lastName(),
			phone: faker.phone.phoneNumber(),
			email: faker.internet.email()
		}
	}

	var data = {
			users: nLoop(10).map(aPerson)
	}

	var server = jsonServer.create()
	var router = jsonServer.router(data)
	var middlewares = jsonServer.defaults()

	// Set default middlewares (logger, static, cors and no-cache)
	server.use(middlewares)

	server.set('jwtTokenSecret', 'bgINB4atOxd8SMNvtOTDxg')
	server.set('userId', 'test@test.com')

	var expires = moment().add('days', 7).valueOf()
	var token = jwt.sign({ 
		iss: server.get('userId'),
		exp: expires
	}, server.get('jwtTokenSecret'))

	// Add custom routes before JSON Server router
	server.get('/echo', function (req, res) {
		res.jsonp(req.query)
	})

	server.post('/auth/validate_token/', (req, res) => {
		if (req.body.email == 'test@test.com' && req.body.password == 'test') {
			res.status(200)
					.json({token: token})
		} else {
			res.sendStatus(403)
		}
	})

	server.post('/auth/sign_in', function (req, res) {
		res.set({
			'Expires':      expires,
			'access-token': token,
			'token-type':   'Bearer',
			'expiry':       expires,
			'client':       'V7EN7LSRYAbpE_-c5PvRSw',
			'uid':          server.get('userId')
		})

		res.json({
			"data": {
				"uid": server.get('userId'),
				"provider": "email",
				"email": server.get('userId'),
				"favorite_color": null,
				"id": 6
			}
		})
	})

	server.delete('/auth/sign_out', function (req, res) {
		res.json({ "success": true })
	})

	// Use default router
	server.use(router)
	server.listen(3010, function () {
		console.log('JSON Server is running on localhost:3010')
	})

headers from postman:

	Access-Control-Allow-Credentials →true
	Access-Control-Allow-Origin →chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
	Cache-Control →no-cache
	Connection →keep-alive
	Content-Length →142
	Content-Type →application/json; charset=utf-8
	Date →Fri, 20 May 2016 22:54:17 GMT
	ETag →W/"8e-rSsVlXMHretJT9EANZhtxA"
	Expires →1464389523686
	Pragma →no-cache
	Vary →Origin, Accept-Encoding
	X-Powered-By →Express
	access-token →eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNDY0Mzg5NTIzNjg2LCJpYXQiOjE0NjM3ODQ3MjN9.p2QnbB8E7_NdyOo3lv1MKrjT383gA_DMO1k7GbZdlGI
	client →V7EN7LSRYAbpE_-c5PvRSw
	expiry →1464389523686
	token-type →Bearer
	uid →test@test.com

Would looooove some insight into this as I'm super stumped.

**Comment by stephenmmcleod** [comment]
😄   Well I guess I've learned a little bit about how CORS works!  

(which is to say, I needed to set Access-Control-Expose-Headers for all the custom headers)

**Comment by mikeover** [comment]
How exactly did you do that @stephenmmcleod ?
