### ISSUE TITLE
Use with Passport

### ISSUE THREAD

**Issue by luandro** [lynndylanhurley/redux-auth#6]
This is an awesome idea, congrats!
Can the [Passport](http://passportjs.org/) library be used? Are there any plans on supporting it.

**Comment by lynndylanhurley** [comment]
This is just the client side. Passport would be the server-side component, similar to [the omniauth library](https://github.com/intridea/omniauth) that is used by the [ruby server side implementation](https://github.com/lynndylanhurley/devise_token_auth). I'm currently using ruby for my own APIs, and I don't have any immediate plans to port the server implementation over to node.js.

**Comment by luandro** [comment]
Got it thx!
