### ISSUE TITLE
Custom REST Calls - (Needs PR?)

### ISSUE THREAD

**Issue by ChrisCates** [lynndylanhurley/redux-auth#64]
I'm looking at the fetch request and noticed I can't do anything except `GET` requests.

Is there some way to add a custom `method` and `body` to the `fetch` request? I would like to know if that's possible. (Based on what I'm looking at in `./src/utils/fetch.js` I need to refactor with multiple params.

**Comment by ChrisCates** [comment]
And I'm more then happy to do a PR if it's not possible.

**Comment by ChrisCates** [comment]
Just noticed that you can get the authHeaders in the cookie...

**Comment by yury-dymov** [comment]
DELETE example:
fetch(`${getAPIUrl()}/comments/${type}/${id}`,
    {
      headers: {
        'Accept': 'application/json'
      },
      method: 'delete'
    })
