### ISSUE TITLE
HMR not working with Redux-Auth

### ISSUE THREAD

**Issue by ChrisCates** [lynndylanhurley/redux-auth#65]
Hey, not sure how to debug this.

But whenever I use HMR. I get this following issue:

This happened after implementing redux-auth

```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
```

**Comment by lynndylanhurley** [comment]
@ChrisCates - can you try this again? This is working for me in the [demo project](https://github.com/lynndylanhurley/redux-auth-demo).
