### ISSUE TITLE
r is not a function

### ISSUE THREAD

**Issue by leon-wbr** [lynndylanhurley/redux-auth#69]
I'm trying to integrate this into react-redux-starter-kit and when injecting the reducer, it's giving me the error that r is not a function.

```
// reducers.js
...
const auth = configureAuth(
  {apiUrl: 'http://localhost:3000'},
  {serverSideRendering: false, cleanSession: true, clientOnly: true}
);

export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    form: formReducer,
    auth,
    router,
    ...asyncReducers
  })
}

...

// main.js
...
let render = (routerKey = null) => {
  const routes = require('./routes/index').default(store)

  ReactDOM.render(
    <div>
      <AuthGlobals />
      <AppContainer
        store={store}
        history={history}
        routes={routes}
        routerKey={routerKey}
      />
    </div>,
    MOUNT_NODE
  )
}
...
```

Maybe I'm doing this all wrong. If so, please tell me how to do it the right way.

https://github.com/davezuko/react-redux-starter-kit

**Comment by yury-dymov** [comment]
@leon-wbr you are passing configureAuth (I assume it is configure) as a reducer, which is not correct. You need to pass authStateReducer and afterwards dispatch configure as redux action. Please refer examples.

**Comment by leon-wbr** [comment]
@yury-dymov I'm using a different boilerplate now and it works fine. Thank you. To save another issue topic - do you know if it's possible to add fields to the sign up without modifying the source?

**Comment by yury-dymov** [comment]
@leon-wbr, I don't think so but you can copy-paste to your project
https://github.com/lynndylanhurley/redux-auth/blob/master/src/views/default/EmailSignUpForm.js

change this line
`import { emailSignUpFormUpdate, emailSignUp } from "../../actions/email-sign-up";`

to

`import { emailSignUpFormUpdate, emailSignUp } from "redux-auth";`

and add whatever you need
