### ISSUE TITLE
Client-only (non-universal) support

### ISSUE THREAD

**Issue by bruz** [lynndylanhurley/redux-auth#7]
First, thank you for this wonderful library. It's been a joy to start playing with it and have such great documentation to work from.

I'm wondering how doable it would be currently to use it in a non-universal app. I assume it's conceptually possible since that appears to be how ng-token-auth works, but I'm curious to hear what you think it'd take to support that, if you think it'd be worthwhile to support that usage. I may be volunteering a future pull request if you're interested in this and think it wouldn't be too daunting.

**Comment by lynndylanhurley** [comment]
Hi @bruz - I'm working on this right now actually. This will launch alongside react-native support. I hope to have this live early next week.

**Comment by bruz** [comment]
Excellent, that's great news!

**Comment by afhammad** [comment]
@lynndylanhurley, any ETA on this?

**Comment by lynndylanhurley** [comment]
@afhammad - I'm at work on this now. It's more work than I'd originally planned, and the holidays set me back a bit. No ETA, but it's my highest priority.

**Comment by afhammad** [comment]
@lynndylanhurley I appreciate the effort. I had replace redux-auth with some custom components due to time constraints on my end but I will give it another shot once this is out. 

Let me know if you need any help testing.

**Comment by selbekk** [comment]
+1 on this

**Comment by themouette** [comment]
Not sure if this is a blocking part, but to ensure browser and server side authentication, I find https://github.com/mjrussell/redux-auth-wrapper to be useful.

In current implementation, if the user changes authentication status (in the browser), it is the developer responsibility to redirect, with redux-auth-wrapper, every time authentication changes, permissions are reevaluated.

**Comment by jpkleemans** [comment]
+1
