### ISSUE TITLE
fetch not working in dispatch

### ISSUE THREAD

**Issue by leon-wbr** [lynndylanhurley/redux-auth#70]
Am I doing something wrong? I'm calling redux-auths fetch function to retrieve all user information in our format from our REST API, but it's not authenticating properly. I swear it was working, what's wrong now?

```
Started GET "/users/me" for ::1 at 2016-08-04 20:42:00 +0200
Processing by UsersController#show as JSON
  Parameters: {"user_id"=>"me", "user"=>{}}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.0ms)
Filter chain halted as :authenticate_user! rendered or redirected
Completed 401 Unauthorized in 6ms (Views: 3.2ms | ActiveRecord: 0.0ms)
```

```
export function fetchUser(id = 'me') {
  return function (dispatch) {
    dispatch(requestUser(id))

    return fetch(`http://localhost:3000/users/${id}`, {
      headers: {
        "Accept": "application/json",
        "Content-Type": "application/json"
      }})
      .then(response => response.json())
      .then(json =>
        console.log(json)
        //dispatch(receiveUser(id, json))
      )
  }
}
```
```
...
componentDidMount(){
    this.props.loadSettings();
  }
...

UserSettings = reduxForm({
  form: 'user',
  fields: ['username', 'email']
},
state => ({
  initialValues: state.user.currentUser,
  user: state.user.currentUser
}),
{
  loadSettings: fetchUser
})(UserSettings)

export default UserSettings;
```

Edit: I found out that the token header is sent, but the token itself is undefined.

**Comment by leon-wbr** [comment]
I figured out that it was because client only authentication isn't implemented yet.

**Comment by lynndylanhurley** [comment]
Client-only authentication should have been implemented in #50. Have you tried setting the `clientOnly` param in the config block?

https://github.com/lynndylanhurley/redux-auth#configure

**Comment by leon-wbr** [comment]
This is my configure now. On sign in, the authorization token is given, but the request still sends `authorization: bearer undefined`.

```
function renderApp() {
  store.dispatch(configure(
    {apiUrl: "http://127.0.0.1:3000"},
    {clientOnly: true, cleanSession: true}
  )).then(() => {
    ReactDOM.render(
      <Provider store={store} key="provider">
        <App />
      </Provider>,
      document.getElementById('react-root')
    )
  });
}
```

**Comment by yury-dymov** [comment]
@leon-wbr take a look https://github.com/yury-dymov/redux-oauth-client-demo, hope it helps :)

**Comment by leon-wbr** [comment]
@yury-dymov Thanks, but no luck so far! I suppose it could be due to me not dispatching fetch, but if I wrap it in a dispatch I get an error `Error: Actions must be plain objects. Use custom middleware for async actions.`

**Comment by yury-dymov** [comment]
@leon-wbr, this is correct, you can't use both libraries :) I am sorry that dispatch is required for fetch but I need to update headers in redux store and I can't do that without dispatching

**Comment by leon-wbr** [comment]
It was actually an issue with my server's CORS. I was accepting all headers, but not exposing the relevant ones. Sorry for wasting your time.
