### ISSUE TITLE
Client only does not work when no redirectHeaders are set

### ISSUE THREAD

**Issue by 2easy** [lynndylanhurley/redux-auth#73]
I don't really know how to use this client only version. Doing exactly as documented I get "No credentials." error.

From code analisys i can tell that I should be redirected from some request - not really know why.
If i've got code on cdn, I just want it to start on login page, no redirection needed. I've got rails API with devise token auth, and it accepts requests to /auth/sign_in without any token, but your code seems to need it from headers to work. Am I doing sth wrong, or this is a bug?

**Comment by yury-dymov** [comment]
Hi @2easy,

it is [not clear if this library supports client-side only](https://github.com/lynndylanhurley/redux-auth/issues/70) version but you can give a try [redux-oauth](https://github.com/yury-dymov/redux-oauth). Client-side only example lives [here](https://github.com/yury-dymov/redux-oauth-client-demo).

**Comment by 2easy** [comment]
Thanks, I'll check it out!

**Comment by leon-wbr** [comment]
Hi,

this library actually supports client-side only.  Make sure your CORS headers are correct first of all (especially the exposed headers), then configure your app as follows:

```
function renderApp() {
  store.dispatch(configure(
    {apiUrl: "http://dev.piczel.tv:3000"},
    {serverSideRendering: false, cleanSession: true}
  )).then(() => {
    ReactDOM.render(
      <Provider store={store} key="provider">
        <App />
      </Provider>,
      document.getElementById('react-root')
    )
  });
}
```

I think you can set the storage to localStorage as well, but our application is working that way. Your problem is likely to be related to CORS, though.

**Comment by 2easy** [comment]
actually the call to the api is not even made. 

const store = configureStore()
const history = syncHistoryWithStore(browserHistory, store)

const renderAppWithAuth = () => store.dispatch(configure(
      {apiUrl: config.apiUrl.domain},
      {clientOnly: true, cleanSession: true}
)).then(({redirectPath, blank} = {}) => {
  if (blank) {
    return <noscript />
  } else {
    return ( <Root store={store} history={history} /> )
  }
})

 action @ 11:14:51.547 SET_ENDPOINT_KEYS 
index.js?9640:164  prev state Object {authStateReducer: Map, entities: Object, pagination: Object, errorMessage: null, routing: Object}
index.js?9640:168  action Object {type: "SET_ENDPOINT_KEYS", endpoints: Array[1], currentEndpointKey: "default", defaultEndpointKey: "default"}currentEndpointKey: "default"defaultEndpointKey: "default"endpoints: Array[1]0: "default"length: 1__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()includes: includes()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()values: values()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Objecttype: "SET_ENDPOINT_KEYS"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
index.js?9640:176  next state Object {authStateReducer: Map, entities: Object, pagination: Object, errorMessage: null, routing: Object}
index.js?9640:152  action @ 11:14:51.558 AUTHENTICATE_ERROR 
index.js?9640:164  prev state Object {authStateReducer: Map, entities: Object, pagination: Object, errorMessage: null, routing: Object}
index.js?9640:168  action Object {type: "AUTHENTICATE_ERROR", errors: Array[1]}errors: Array[1]0: "No credentials."length: 1__proto__: Array[0]type: "AUTHENTICATE_ERROR"__proto__: Object
index.js?9640:176  next state Object {authStateReducer: Map, entities: Object, pagination: Object, errorMessage: null, routing: Object}

**Comment by leon-wbr** [comment]
There's no call to the API at that point. The calls are made on sign in, sign up, etc.

**Comment by 2easy** [comment]
Ok, thanks. Will check the issue with CORS in mind.

**Comment by 2easy** [comment]
Ok, I've investigated a little bit more. This has nothing to do with CORS.

As I described Single Page App is downloaded from sever as static asset. There are no headers set to 'access-token', 'uid' and others. Due to that the code from configure action gets evaluated with initialCredentials as null (and later in './utils/client-settings.js' also is set to null), therefore function applyConfig from './utils/client-settings.js' throws an exception "No credentials.".

The question is why there is made such assumption, that there will be any redirectHeaders on the request? Why is necessary before making any request to the API which require auth?

**Comment by templeman15** [comment]
@2easy I'm having the exact same problem and came to the same conclusion. Did you ever find a fix?

**Comment by 2easy** [comment]
@templeman15 yep. https://github.com/mjrussell/redux-auth-wrapper

**Comment by jclif** [comment]
@lynndylanhurley It seems like clientOnly is still causing some problems across a few issues; have you been able to replicate any of the issues?
